languageCode = "en"
languageName = "English"
weight = 1

[author]
  name = "Santiago"
  headline = "Electrical Engineer"
  bio = "Embedded systems, FPGA design, RF & antenna simulation, signal processing."
  links = [
    { github = "https://github.com/scast3" },
    { linkedin = "https://www.linkedin.com/in/santiagoalejandro-castillo/" }
  ]